<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <Version>0.1.7</Version>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>Assets/Icons/athena.ico</ApplicationIcon>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <DiscoverEditorConfigFiles>false</DiscoverEditorConfigFiles>
  </PropertyGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets/Sprites/*.png" />
    <AvaloniaResource Include="Assets/Icons/*.png" />
    <AvaloniaResource Include="Assets/Icons/*.ico" />
    <Content Include="Assets/Sprites/*.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    </Content>
    <Content Include="Assets/Sprites/*.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    </Content>
    <Content Include="Assets/Icons/*.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    </Content>
    <Content Include="Assets/Icons/*.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    </Content>
    <Content Include="Assets/Icons/*.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    </Content>
    <Content Include="Assets/Sounds/*.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.7" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.7" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.7" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.7" />
  </ItemGroup>

</Project>
